from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('start/', views.start, name='start'),
    path('timetable/<int:pk>/', views.timetable, name='timetable'),
    path('timetable_week/<int:pk>/', views.timetable_week, name='timetable_week'),
    path('timetable_month/<int:pk>/', views.timetable_month, name='timetable_month'),
    path('lesson_new/', views.lesson_new, name='lesson_new'),
    path('<page>/<fix_day>/lesson_edit/<int:pk>/', views.lesson_edit, name='lesson_edit'),
    path('<page>/<fix_day>/lesson_edit/<int:pk>/delete/', views.lesson_delete, name='lesson_delete'),
    path('settings/', views.settings, name='settings'),
    path('settings/<unit>/', views.settings, name='settings'),
    path('tasks/', views.tasks, name='tasks'),
    path('task_new/', views.task_new, name='task_new'),
    path('task_new_lesson/<lesson>/<date>/<time>/<menu>/<info>/', views.task_new_lesson, name='task_new_lesson'),
    path('task_edit/<int:pk>/', views.task_edit, name='task_edit'),
    path('task_edit/<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('subject_new/', views.subject_new, name='subject_new'),
    path('subjects/', views.subjects, name='subjects'),
    path('subject_edit/<int:pk>/', views.subject_edit, name='subject_edit'),
    path('subject_double/<int:pk>/', views.subject_double, name='subject_double'),
    path('subject_edit/<int:pk>/delete', views.subject_delete, name='subject_delete'),
    path('exams/', views.exams, name='exams'),
    path('exam_edit/<int:pk>/', views.exam_edit, name='exam_edit'),
    path('exam_new/', views.exam_new_1, name='exam_new_1'),
    path('exam_new/<examination>/', views.exam_new_2, name='exam_new_2'),
    path('exam_edit/<int:pk>/delete', views.exam_delete, name='exam_delete'),
    path('plans/', views.plans, name='plans'),
    path('plan_edit/<int:pk>/', views.plan_edit, name='plan_edit'),
    path('plan_new/', views.plan_new, name='plan_new'),
    path('plan_edit/<int:pk>/delete', views.plan_delete, name='plan_delete'),
    path('info/<int:pk>/', views.info, name='info'),
    path('notes_lesson/<int:pk>/', views.notes_lesson, name='notes_lesson'),
    path('notes_task/<int:pk>/', views.notes_task, name='notes_task'),
    path('notes_exam/<int:pk>/', views.notes_exam, name='notes_exam'),
    path('notes_plan/<int:pk>/', views.notes_plan, name='notes_plan'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('import/', views.import_timetable, name='import_timetable'),
    path('feedback/', views.feedback, name='feedback')
]
