# Generated by Django 2.2.24 on 2021-11-03 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2021-11-03')),
                ('end_date', models.DateField(default='2021-11-03')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('end_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_short', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher', models.CharField(blank=True, default='', max_length=200)),
                ('teachershort', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#FF81F3', max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('classroom', models.CharField(blank=True, default='', max_length=200)),
                ('weeks', models.CharField(default='12', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeating_weeks', models.IntegerField(default=1)),
                ('first_lesson_start', models.TimeField(default=datetime.time(9, 0))),
                ('lesson_length', models.IntegerField(default=95)),
                ('break_length', models.IntegerField(default=15)),
                ('max_lessons', models.IntegerField(default=6)),
                ('theme', models.CharField(default='#FF81F2', max_length=7)),
                ('sub_color', models.CharField(default='#FFAFFC', max_length=7)),
                ('start_date', models.DateField(default='2021-11-03')),
                ('end_date', models.DateField(default='2021-11-03')),
                ('exams_date', models.DateField(blank=True, null=True)),
                ('homepage', models.CharField(default='timetable', max_length=50)),
                ('university', models.CharField(default='НГУ', max_length=200)),
                ('holidays', models.ManyToManyField(blank=True, to='MSP.Holiday')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=500)),
                ('color', models.CharField(default='#FF81F3', max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_short', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher', models.CharField(blank=True, default='', max_length=200)),
                ('teachershort', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#FF81F3', max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('classroom', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hometask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('hometask', models.CharField(blank=True, max_length=200, null=True)),
                ('done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Lesson')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('examination', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Lesson')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('select_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('weekday', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
