# Generated by Django 2.2.19 on 2021-03-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Lesson'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.Lesson'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='hometask',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
