# Generated by Django 3.1.3 on 2021-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0004_hometask_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date_conv',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_time_conv',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time_conv',
        ),
        migrations.AddField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hometask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='hometask',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
