# Generated by Django 3.1.3 on 2021-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0005_auto_20210304_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teachershort',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
