# Generated by Django 3.1.3 on 2021-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0006_lesson_teachershort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='color',
            field=models.CharField(default='#FFB546', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
