# Generated by Django 3.1.3 on 2021-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0008_auto_20210311_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='#FF81F2', max_length=7),
        ),
    ]
