# Generated by Django 3.1.3 on 2021-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0009_auto_20210311_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='break_length',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='settings',
            name='lesson_length',
            field=models.IntegerField(default=95),
        ),
    ]
