# Generated by Django 3.1.3 on 2021-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0010_auto_20210311_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='weekday',
            field=models.IntegerField(default=0),
        ),
    ]
