# Generated by Django 3.1.3 on 2021-04-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0011_lesson_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.time'),
        ),
    ]
