# Generated by Django 3.1.3 on 2021-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0012_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teachershort',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
