# Generated by Django 3.1.3 on 2021-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0015_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
