# Generated by Django 3.1.3 on 2021-04-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0016_auto_20210404_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='settings',
        ),
    ]
