# Generated by Django 3.1.3 on 2021-04-06 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0020_auto_20210406_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
