# Generated by Django 3.1.3 on 2021-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0021_auto_20210406_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-04-07'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='07.04.2021'),
        ),
    ]
