# Generated by Django 3.1.3 on 2021-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0023_auto_20210413_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher', models.CharField(blank=True, default='', max_length=200)),
                ('teachershort', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#FF81F3', max_length=200)),
                ('weekday', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200)),
                ('classroom', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='select_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='color',
            field=models.CharField(default='#FF81F3', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
