# Generated by Django 3.1.3 on 2021-04-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0025_auto_20210414_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.lesson'),
        ),
    ]
