# Generated by Django 3.1.3 on 2021-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0026_auto_20210414_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
