# Generated by Django 3.1.3 on 2021-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0027_hometask_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-04-15'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='15.04.2021'),
        ),
    ]
