# Generated by Django 3.1.3 on 2021-04-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0028_auto_20210415_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='select_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.subject'),
        ),
    ]
