# Generated by Django 3.1.3 on 2021-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0029_hometask_select_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='color',
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-04-20'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='20.04.2021'),
        ),
    ]
