# Generated by Django 3.1.3 on 2021-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0030_auto_20210420_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='weeks',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='weeks',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
