# Generated by Django 3.1.3 on 2021-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0031_auto_20210420_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sub_color',
            field=models.CharField(default='#FFAFFC', max_length=7),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-04-21'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='21.04.2021'),
        ),
    ]
