# Generated by Django 3.1.3 on 2021-04-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0032_auto_20210421_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='select_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weeks',
            field=models.CharField(default='12', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-04-23'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='23.04.2021'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weeks',
            field=models.CharField(default='12', max_length=20),
        ),
    ]
