# Generated by Django 3.1.3 on 2021-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0033_auto_20210423_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
