# Generated by Django 3.1.3 on 2021-04-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0034_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examination',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MSP.lesson'),
        ),
    ]
