# Generated by Django 3.1.3 on 2021-04-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0035_auto_20210423_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam',
            new_name='topic',
        ),
    ]
