# Generated by Django 3.1.3 on 2021-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0039_auto_20210426_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
