# Generated by Django 3.1.3 on 2021-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0040_auto_20210426_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(default='#FF81F3', max_length=200),
        ),
    ]
