# Generated by Django 3.1.3 on 2021-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0041_plan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-05-01'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='01.05.2021'),
        ),
    ]
