# Generated by Django 3.1.3 on 2021-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0042_auto_20210501_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='weeks',
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-05-05'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='05.05.2021'),
        ),
    ]
