# Generated by Django 3.1.3 on 2021-06-20 17:37

from django.db import migrations, models
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0045_auto_20210513_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='location_lat',
            field=osm_field.fields.LatitudeField(null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='plan',
            name='location_lon',
            field=osm_field.fields.LongitudeField(null=True, validators=[osm_field.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-06-21'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='2021-06-21'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
