# Generated by Django 3.1.3 on 2021-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0046_auto_20210621_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='exams_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-06-24'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='2021-06-24'),
        ),
    ]
