# Generated by Django 3.1.3 on 2021-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0047_auto_20210624_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='homepage',
            field=models.CharField(default='timetable', max_length=50),
        ),
    ]
