# Generated by Django 3.1.3 on 2021-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0048_settings_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='university',
            field=models.CharField(default='НГУ', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default='2021-07-04'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default='2021-07-04'),
        ),
    ]
