# Generated by Django 3.1.3 on 2021-07-04 11:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0049_auto_20210704_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='holidays',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
