# Generated by Django 3.1.3 on 2021-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSP', '0051_auto_20210704_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='MSP.Holiday'),
        ),
    ]
